services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secretpassword}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3307:3306"
  app:
    image: php:8.2-apache
    container_name: symfony_app
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./apache.conf:/etc/apache2/sites-enabled/000-default.conf
    environment:
      - APP_ENV=prod
    depends_on:
      - database
    networks:
      - symfony_network

volumes:
  database_data:

networks:
  symfony_network:
    driver: bridge