- name: Déploiement Symfony via Docker (prod)
  hosts: all
  become: yes
  vars:
    symfony_project_dir: "/var/www/html/Vigisoft"

  tasks:
    - name: Vérifie que Docker est installé
      command: docker --version
      register: docker_version
      failed_when: false
      changed_when: false

    - name: Installer Docker si non installé
      apt:
        name: docker.io
        state: present
      when: docker_version.rc != 0

    - name: Cloner le dépôt Symfony
      git:
        repo: "https://github.com/enzodaloia/Vigisoft.git"
        dest: "{{ symfony_project_dir }}"
        version: main
        force: yes
        update: yes

    - name: Lancer le build et démarrer les conteneurs
      command: docker compose -f docker-compose.prod.yaml up -d --build
      args:
        chdir: "{{ symfony_project_dir }}"
